# Generated by Django 5.2.7 on 2025-10-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='roll_no',
        ),
    ]
