# Generated by Django 5.2.7 on 2025-10-22 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_rename_phone_student_roll_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='hostelrule',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hostel_admin', models.BooleanField(default=False)),
                ('admin_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('hostel_manager', 'Hostel Manager'), ('attendance_manager', 'Attendance Manager'), ('viewer', 'Viewer')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
